from main import Employee,FulltimeEmployee
worker2 = Employee("eli",15000,"haifa")
# repr(worker2)
worker3 = FulltimeEmployee("R&D", "Sanjin", 50000)
worker2.bonus()
salary = worker3.get_salary()
worker2.get_info()
worker3.get_total_pay(230)
worker3.get_info()
worker3.salary_after_tax(salary)
